### ISSUE TITLE
docker get error after run for a while...

### ISSUE THREAD

**Issue by digjack** [wechaty/wechaty#2320]
## Enviroment:
  1. Wechaty version: 1.10.4
  2. Linux x64 version 4.4.0-105-generic memory 475/992 MB
  3. Docker: true
  4. Node version: v16.13.0
  5. Tcp IPC TEST: PASS

## error report: 

```
16:18:42 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
GError: from(`object`): [object Object]
    at Function.from (file:///wechaty/node_modules/gerror/src/gerror/gerror.ts:77:15)
    at PuppetWeChat.<anonymous> (file:///wechaty/src/wechaty-mixins/puppet-mixin.ts:203:41)
    at PuppetWeChat.emit (node:events:390:28)
    at PuppetWeChat.emit (node:domain:475:12)
    at PuppetWeChat.emit (file:///wechaty/node_modules/wechaty-puppet/src/puppet/puppet-skeleton.ts:137:18)
    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:19)
    at Watchdog.emit (node:events:390:28)
    at Watchdog.emit (node:domain:475:12)
    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 2,
  details: 'GError: from(`object`): [object Object]\n' +
    '    at Function.from (file:///wechaty/node_modules/gerror/src/gerror/gerror.ts:77:15)\n' +
    '    at PuppetWeChat.<anonymous> (file:///wechaty/src/wechaty-mixins/puppet-mixin.ts:203:41)\n' +
    '    at PuppetWeChat.emit (node:events:390:28)\n' +
    '    at PuppetWeChat.emit (node:domain:475:12)\n' +
    '    at PuppetWeChat.emit (file:///wechaty/node_modules/wechaty-puppet/src/puppet/puppet-skeleton.ts:137:18)\n' +
    '    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:19)\n' +
    '    at Watchdog.emit (node:events:390:28)\n' +
    '    at Watchdog.emit (node:domain:475:12)\n' +
    '    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'
}
ERROR: Bot exited with code 1
```

## other report info 

```
### 1. source code of ding-dong-bot.ts

#!/usr/bin/env -S node --no-warnings --loader ts-node/esm
/**
 * Wechaty - Conversational RPA SDK for Chatbot Makers.
 *  - https://github.com/wechaty/wechaty
 */
// https://stackoverflow.com/a/42817956/1123955
// https://github.com/motdotla/dotenv/issues/89#issuecomment-587753552
import 'dotenv/config.js'

import {
    Contact,
    Message,
    ScanStatus,
    WechatyBuilder,
    Friendship,
    log,
}                  from 'wechaty'
import * as PUPPET          from 'wechaty-puppet'

import qrcodeTerminal from 'qrcode-terminal'

function onLogout (user: Contact) {
    log.info('StarterBot', '%s logout', user)
}

function onScan (qrcode: string, status: ScanStatus) {
    if (status === ScanStatus.Waiting || status === ScanStatus.Timeout) {
        const qrcodeImageUrl = [
            'https://wechaty.js.org/qrcode/',
            encodeURIComponent(qrcode),
        ].join('')
        log.info('StarterBot', 'onScan: %s(%s) - %s', ScanStatus[status], status, qrcodeImageUrl)

        qrcodeTerminal.generate(qrcode, { small: true })  // show qrcode on console

    } else {
        log.info('StarterBot', 'onScan: %s(%s)', ScanStatus[status], status)
    }
}


function onLogin (user: Contact) {
    log.info('StarterBot', '%s login', user)
}

async function onMessage (msg: Message) {
    log.info('StarterBot', msg.toString())
}



const bot = WechatyBuilder.build({
    name: 'vanceee',
    /**
     * How to set Wechaty Puppet Provider:
     *
     *  1. Specify a `puppet` option when instantiating Wechaty. (like `{ puppet: 'wechaty-puppet-whatsapp' }`, see below)
     *  1. Set the `WECHATY_PUPPET` environment variable to the puppet NPM module name. (like `wechaty-puppet-whatsapp`)
     *
     * You can use the following providers locally:
     *  - wechaty-puppet-wechat (web protocol, no token required)
     *  - wechaty-puppet-whatsapp (web protocol, no token required)
     *  - wechaty-puppet-padlocal (pad protocol, token required)
     *  - etc. see: <https://wechaty.js.org/docs/puppet-providers/>
     */
     puppet: 'wechaty-puppet-wechat',

    /**
     * You can use wechaty puppet provider 'wechaty-puppet-service'
     *   which can connect to remote Wechaty Puppet Services
     *   for using more powerful protocol.
     * Learn more about services (and TOKEN) from https://wechaty.js.org/docs/puppet-services/
     */
    // puppet: 'wechaty-puppet-service'
    // puppetOptions: {
    //   token: 'xxx',
    // }
})

bot.on('scan',    onScan)
bot.on('login',   onLogin)
bot.on('logout',  onLogout)
bot.on('message', onMessage)
bot.on('friendship', async function(friendship:Friendship) {
//   const fileHelper = bot.Contact.find({name: 'filehelper'})
  try {
    console.log(`received friend event.`)
    switch (friendship.type()) {
    // 1. New Friend Request
    case PUPPET.types.Friendship.Receive:
      await friendship.accept()
    //   await fileHelper.say('自动通过好友请求，昵称：'+ friendship.contact().name())
      await new Promise(r => setTimeout(r, 1000))
      await friendship.contact().say('你好')
      break

    // 2. Friend Ship Confirmed
    case PUPPET.types.Friendship.Confirm:
      console.log(`friend ship confirmed`)
      break
    }
  } catch (e) {
    console.error(e)
  }
})

bot.start()
    .then(() => log.info('StarterBot', 'Starter Bot Started.'))
    .catch(e => log.error('StarterBot', e))


### 2. directory structor of /bot

total 8
-rw-rw-rw- 1 root root 3388 Nov 27 17:35 ding-dong-bot.ts
-rw-r--r-- 1 root root 2845 Nov 30 15:31 vanceee.memory-card.json

### 3. package.json

cat: /bot/package.json: No such file or directory
No package.json

### 4. directory structor inside /bot/node_modules

ls: cannot access '/bot/node_modules': No such file or directory
No node_modules

### 5. wechaty doctor


  #### Wechaty Doctor

  1. Wechaty version: 1.10.4
  2. Linux x64 version 4.4.0-105-generic memory 475/992 MB
  3. Docker: true
  4. Node version: v16.13.0
  5. Tcp IPC TEST: PASS

```

what open ? what can I do to deal with this error?

**Comment by huan** [comment]
Can you try the `wechaty/wechaty:next` to see if you can reproduce this problem?

**Comment by digjack** [comment]
### run by `wechaty/wechaty:next`  get another error like that

```
WECHATY Environment Variables: 3
WECHATY_DOCKER=1
WECHATY_LOG=INFO
WECHATY_PUPPET=wechaty-puppet-wechat

Starting Docker Container for Wechaty v1.11.24 with Node.js v16.13.1 ...
Working directory: /bot
Executing node --loader=ts-node/esm ding-dong-bot.ts
05:48:08 ERR Puppet resolvePuppetName
Failed to import Wechaty Puppet Provider (WPP) NPM module: "wechaty-puppet-wechat"
Please make sure:
 1. it has been installed correctly. (run `npm install wechaty-puppet-wechat` if it doesn't)
 2. "wechaty-puppet-wechat" is a valid Wechaty Puppet Provider (WPP).

learn more about Wechaty Puppet Providers (WPP) from the official website:
<https://wechaty.js.org/docs/puppet-providers>

05:48:08 ERR StarterBot Error: ERR_PACKAGE_PATH_NOT_EXPORTED /wechaty/node_modules/wechaty-puppet/ ./helper /wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/event.js
```

### The startup command is 
```
 docker run -t -i --privileged --network=host  \
-e WECHATY_LOG="$WECHATY_LOG" -e WECHATY_PUPPET="$WECHATY_PUPPET"  \
--mount type=bind,source="$(pwd)",target=/bot  \
wechaty/wechaty:next ding-dong-bot.ts
```

**Comment by huan** [comment]
> 05:48:08 ERR StarterBot Error: ERR_PACKAGE_PATH_NOT_EXPORTED /wechaty/node_modules/wechaty-puppet/ ./helper /wechaty/node_modules/wechaty-puppet-wechat/dist/esm/src/event.js

Fixed by https://github.com/wechaty/puppet-wechat/commit/5153ae8e33c749841d673fe7098339a878869e99

The Wechaty v1.11.25 should contain the fix of this problem, Please wait our CI to deploy (try again around 1 hour later)

**Comment by digjack** [comment]
### still get chat error  

```
02:24:12 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:390:28)
    at Watchdog.emit (node:domain:475:12)
    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:390:28)\n' +
    '    at Watchdog.emit (node:domain:475:12)\n' +
    '    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'
}
ERROR: Bot exited with code 1

```


 #### Wechaty Doctor

  1. Wechaty version: 1.11.25
  2. Linux x64 version 4.4.0-105-generic memory 357/992 MB
  3. Docker: true
  4. Node version: v16.13.1
  5. Tcp IPC TEST: PASS

**Comment by huan** [comment]
Do you have a  series of steps that can reproduce this problem for every time?

**Comment by xiaogaozi** [comment]
Same issue here, the version information is:

- wechaty: 1.10.4
- wechaty-puppet: 1.11.15
- wechaty-puppet-wechat: 1.11.11

**Comment by gouyanfeng** [comment]
> ### still get chat error
> ```
> 02:24:12 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
> GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
>     at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
>     at Watchdog.emit (node:events:390:28)
>     at Watchdog.emit (node:domain:475:12)
>     at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)
>     at listOnTimeout (node:internal/timers:557:17)
>     at processTimers (node:internal/timers:500:7) {
>   code: 2,
>   details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
>     '    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
>     '    at Watchdog.emit (node:events:390:28)\n' +
>     '    at Watchdog.emit (node:domain:475:12)\n' +
>     '    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
>     '    at listOnTimeout (node:internal/timers:557:17)\n' +
>     '    at processTimers (node:internal/timers:500:7)'
> }
> ERROR: Bot exited with code 1
> ```
> 
> #### Wechaty Doctor
> 1. Wechaty version: 1.11.25
> 2. Linux x64 version 4.4.0-105-generic memory 357/992 MB
> 3. Docker: true
> 4. Node version: v16.13.1
> 5. Tcp IPC TEST: PASS

02:24:12 WARN PuppetWatchdogAgent start() reset() reason: {"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:390:28)
    at Watchdog.emit (node:domain:475:12)
    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (file:///wechaty/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:390:28)\n' +
    '    at Watchdog.emit (node:domain:475:12)\n' +
    '    at Timeout._onTimeout (file:///wechaty/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'
}
ERROR: Bot exited with code 



微信需要实名认证

**Comment by gouyanfeng** [comment]
同样的报错     微信实名认证后好了

**Comment by sofay** [comment]
how to fix it?

**Comment by lijxug** [comment]
This issue still exists. Anything idea to fix it?
